# -*- coding: utf-8 -*-
"""resnet101_base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gIh80T3cB2kJFHjXeuiejuSDIKkgMPIi
"""

import torch
from torch import nn

from .resnet import resnet50, resnet101

class ResNet101(nn.Module):
    def __init__(self):
        super(ResNet101, self).__init__()
        net = resnet101()
        
        net = list(net.children())
        self.layer0 = nn.Sequential(*net[:3])
        self.layer1 = nn.Sequential(*net[3: 5])
        self.layer2 = net[5]
        self.layer3 = net[6]
        self.layer4 = net[7]

    def forward(self, x):
        layer0 = self.layer0(x)
        layer1 = self.layer1(layer0)
        layer2 = self.layer2(layer1)
        layer3 = self.layer3(layer2)
        layer4 = self.layer4(layer3)
        return layer4